spring:
  profiles: Eureka1
  application:
    name: Eureka
server:
  port: 5555
eureka:
  instance:
    hostname: Eur1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://Eur1:5555/eureka
---
spring:
  profiles: Eureka2
  application:
    name: Eureka
server:
  port: 5553
eureka:
  instance:
    hostname: Eur2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://Eur1:5555/eureka/,http://Eur3:5554/eureka/
---
spring:
  profiles: Eureka3
  application:
    name: Eureka
server:
  port: 5554
eureka:
  instance:
    hostname: Eur3
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://Eur1:5555/eureka/,http://Eur2:5553/eureka/


